// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqhruotbmlyubyxwaaez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxaHJ1b3RibWx5dWJ5eHdhYWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDI0MTAsImV4cCI6MjA2MDE3ODQxMH0.EOQhSUYb6Yd4v2xwuPMiQsyrTnsZBWn962xZq8bOWrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);